spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
#    url: jdbc:mysql://localhost:3306/autehnticationservicedb
#    username: root
#    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: user-auth
  zipkin:
    sender:
      type: web
    service:
      name: zipkin
    baseUrl: http://localhost:9411/zipkin
    locator:
      discovery:
        enabled: true
  sleuth:
    feign:
      enabled: false
      
server:
  port: 9100
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
