spring:
  data:
    mongodb:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
#      database: reminderDb
#      port: 27017
#      host: localhost
  application:
    name: reminder-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411/  
    locator:
      discovery:
        enabled: true
server:
  port: 9500
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
