FROM openjdk:8-alpine
EXPOSE 9100
ADD /target/UserAuthentication-Service-0.0.1-SNAPSHOT.jar UserAuthentication-Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "UserAuthentication-Service-0.0.1-SNAPSHOT.jar"]