spring:
  data:
    mongodb:
#      username: root
#      password: root
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
#      database: noteDb
#      port: 27017
#      host: mongo
  application:
    name: note-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://localhost:9411/zipkin/  
    locator:
      discovery:
        enabled: true
server:
  port: 9300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka